pcdshub/happi

- .landscape.yml
- .travis.yml
- conda-recipe/meta.yaml
- examples/launch_edl.py
- happi/backends.py
- happi/client.py
- happi/device.py
- happi/errors.py
- happi/tests/conftest.py
- happi/tests/test_backends.py
- happi/tests/test_client.py
- happi/tests/test_device.py
* Abstracted all calls to MongoDB so we can switch back and forth between whatever backend we want
* Added backend support for MongoDB and JSON
* Setup landscape.io
* Closes #2 that deals with device comparison
My major concern with the JSON backend is we essentially have to destroy and rewrite the file every edit. I used some file locking functions to make sure we can't write at the same time and corrupt the file, but it still feels kind of scary.
> ENH: Support for JSON 

- .landscape.yml
- .travis.yml
- happi/backends.py
- happi/client.py
- happi/device.py
- happi/tests/test_backends.py
Changes
-------
* Add a convenience method so we can start a new JSON database from scratch
* Cleaned logging and imports
* Updated landscape to only look at useful files
The Bad
-------
* Dropping support for Python 2.x. The repo is so close to working on both, but I can't keep taking 1.5 times longer to write code that works on 2.x. Doesn't feel great as a ton of stuff is implemented with `six`, but it just is not worth the time until we have a valid 2.x application that needs this
> ENH: JSONBackend Initialize

- happi/containers.py
* **PIM** -> `prefix_det`
*  **OffsetMirror** -> `prefix_xy`, `state_prefix`, `in_lines`, `out_lines`
> ENH: Add EntryInfo for PIM, OffsetMirror

- README.md
- conda-recipe/meta.yaml
CI: Add about section for happi conda package at meta.yml
> FIX: Add needed '-c conda-forge' to README.

- .travis.yml
- requirements.txt
- test-requirements.txt
We should still support pip installs for developers
> BLD: Include requirement files

- README.md
> DOC: Update documentation to specify PCDS Anaconda

- happi/client.py
- happi/loader.py
* Downgrade backend log message to DEBUG
* Enhanced logging message since we won't be using the `pprint` option.
> MAINT: Downgrade backend log message to DEBUG

- happi/backends/qs_db.py
The result of nested for loops with the same name for the index variable.
```
Unable to create an object from Questionnaire table Spokesperson Email row 4
```
becomes:
```
Unable to create an object from Questionnaire table motors row 4
```
> FIX: Non-sensical error message

- dev-requirements.txt
- happi/backends/json_db.py
* `pip` requirements were a little out of date
* `JSONBackend` watches to see if you are going to overwrite an existing database. The fear is that someone types `initialize=True` and erases their whole db. However, we shouldn't be scared of writing to an empty file.
> Minor Fixes

- .travis.yml
- happi/device.py
Starting the train! One small `regex` issue which is slightly annoying but it was a private variable...
> Python 3.7

- happi/backends/qs_db.py
- happi/device.py
- happi/loader.py
- happi/tests/test_client.py
- happi/tests/test_loader.py
For `L2S-I` each device will have three screens. I have adjusted the `happi.Device` to have three fields for these. 
Closes #79
> Screen setup

- happi/backends/json_db.py
Change `open()` calls to use `with` blocks 
Warnings in other test suites indicated that these file handles were not being closed.
> MNT: use with blocks for json backend file operations

- happi/client.py
- happi/tests/test_client.py
Added function to list choices for a given field that user can search for: `Client.list_choices`
Will allow user to know what beamlines, prefixes, names, etc. will return results
`test_client.test_list_choices`
docstring of `Client.list_choices`
usage: Client.list_choices('beamline')
returns: list of beamlines the user can search for and will return results
> List choices for field

- happi/cli.py
- happi/device.py
- Add an `add` command for cli, e.g. `happi add` to start an interactive device adder
- Add an `edit` command for cli, e.g. `happi edit im3l0 location=750 prefix=IM3L0:PPM`
- Change `search` command syntax to be simpler (more like `edit`)
- Add a `load` command for cli, e.g. `happi load im3l0 im1l1` -> `IPython` session
plus other changes made in dev to "get it working"
I got really upset trying to remember how to do all of these in the shell
- `add` will help us populate the database
- `edit` will help us fix mistakes
- `load` will help us debug classes and see if the entries are correct
Only live tests so far, should not be merged yet
This will need to be added to the docs cli page
> ENH: add cli commands, update required fields, fix issues

- conda-recipe/meta.yaml
- happi/backends/json_db.py
- happi/cli.py
- happi/device.py
- happi/tests/conftest.py
- happi/tests/test_backends.py
- happi/tests/test_cli.py
- happi/tests/test_client.py
- happi/tests/test_device.py
- happi/tests/test_loader.py
> FIX/TST: initialize database if it does not yet exist + fix all tests

- dev-requirements.txt
- happi/backends/mongo_db.py
- happi/tests/conftest.py
- happi/tests/test_backends.py
Closes #111
Tests now require both pymongo + mongomock to test the mongo backend.
> TST: make pymongo truly optional

- happi/device.py
- happi/tests/test_device.py
I think this will be a good spot to jump on #106 for other lab's use - want to give that a go @hhslepicka?
> REF: remove metaclass for HappiItem + allow for easy dict interface

- happi/backends/json_db.py
- happi/client.py
Closes #93 
... and then some, in an attempt to give more information to the user about their misconfiguration.
> FIX: bad user configuration issues

- happi/backends/core.py
- happi/backends/json_db.py
- happi/backends/mongo_db.py
- happi/client.py
Switching to a base class as in this case of the backend there is no particular reason (as far as I could tell) for it to be a metaclass.
Tests are passing.
> REF: Move from metaclass Backend to base class.

- docs/source/backends.rst
- docs/source/client.rst
- docs/source/conf.py
- docs/source/conventions.rst
Documentation build was broken.
We must have the docs.
Locally
Guess where? At the Docs! 😜
> DOC: Fix docs build

- .travis.yml
- dev-requirements.txt
- setup.py
No way this'll work on the first try. More tomorrow.
> CI: tweak CI and add python 3.8

- happi/device.py
- happi/tests/test_device.py
Closes #1
Also, my first attempt at using the new `gh` CLI to list issues + create a PR.
Apologies if this doesn't turn out as I expect...
> ENH: allow copying of devices

- happi/client.py
Fixes an annoying deprecation warning.
> FIX: internally using deprecated all_devices

- happi/backends/__init__.py
- happi/backends/qs_db.py
Closes #132 by reducing verbosity to debug.
> FIX: Reduce to debug messages for unavailable backends.

- MANIFEST.in
> BLD: add requirements.txt to the MANIFEST.in.

- docs/source/releases.rst
Tag would contain fixes from @klauer and @hhslepicka
> DOC: release notes for v1.6.1

- docs/source/releases.rst
Includes all the recent updates/fixes that @cristinasewell worked on.
We can also include #157 here, but it is ok if that waits for the next tag.
> DOC: add release notes for v1.7.0

- docs/source/releases.rst
Document @cristinasewell 's fixes from #160 and #161.
I would like to get into the habit of tagging/releasing more frequently in our repositories, especially for bugfixes, to keep the tagged environments relevant and increase their usage over dev.
> DOC: document recent bugfixes for release v1.7.1

- happi/tests/test_cli.py
Added more test cases for some cli functionalities 
Trying to close #162 
```
Has only been tested locally: 
python run_tests.py
coverage run run_tests.py 
coverage report -m
```
N/A
> TST: Cli testing

- happi/backends/qs_db.py
The qs database isn't quite as orderly as I would like. There are some edge cases, notably with the xcsdaq13 and xcsdaq18 experiments. This try/except kluge tries to randomwalk us towards the correct entries.
Database is screwy, some of these experiments don't load
Minimally, probably should wait to merge
> MNT: handle edge cases in qs loader

- docs/source/releases.rst
Just the super cool fuzzy finding feature for now, version numbers are cheap
> DOC: v1.8.0 release notes

- docs/source/releases.rst
Questionnaire updates/fixes/cleanup for LCLS from @klauer
> DOC: release notes for v1.8.1

- docs/source/releases.rst
- Add notes for @cristinasewell's recent fixes and pick a bugfix number
- Add notes for the previous hotfix release that didn't get added to the docs page
- Tagging is good, release notes are good
> DOC: release notes for v1.8.3 and v1.8.2 hotfix

- README.md
Add documentation link to README
I actually didn't realize y'all had documentation beyond the README until @klauer pointed it out. Perhaps other people are also clueless...
> add documentation link to readme

- happi/containers.py
resolves #198 
see #198 
Tested locally. Willing to add tests but I need guidance from maintainers :sweat_smile: 
Willing to add documentation but I need guidance from maintainers.
> FIX: HappiRegistry call load again if requested item not found

- docs/Makefile
- docs/source/api.rst
- docs/source/cli.rst
- docs/source/client.rst
- docs/source/conf.py
- docs/source/containers.rst
- docs/source/index.rst
- examples/qt/listview.py
- examples/qt/treeview.py
- happi/backends/__init__.py
- happi/backends/core.py
- happi/backends/json_db.py
- happi/backends/mongo_db.py
- happi/backends/qs_db.py
- happi/cli.py
- happi/client.py
- happi/containers.py
- happi/errors.py
- happi/item.py
- happi/loader.py
- happi/qt/model.py
- happi/tests/test_cli.py
- happi/tests/test_client.py
- happi/tests/test_device.py
- run_tests.py
- setup.cfg
- setup.py
- versioneer.py
Follow-up to #193 
Late - but still appreciated! - review by @ZryletTC :)
Built docs locally.
It is documentation.
Thoughts on the top-level sections? 
https://github.com/pcdshub/happi/pull/193#discussion_r552330581
Built docs from last PR were pushed up manually: https://pcdshub.github.io/happi
> DOC: further cleanup (followup PR)

- docs/source/releases.rst
Release notes for bugfix release
Note: add zrylettc to contributors if #196 is merged first
> DOC: add release notes for v1.8.4

- .travis.yml
- conda-recipe/build.sh
- conda-recipe/meta.yaml
- dev-requirements.txt
Upgrade happi CI to latest, shared standards.
Docs build is failing on merge, for some reason. Let's get this out of the way first.
> CI: upgrade to latest shared standard

- docs/source/releases.rst
Write release notes from the last month of merged pull requests
Tagging day
@untzag we'll be tagging the fixes/features you contributed today
> DOC: release notes for v1.9.0

- README.md
- dev-requirements.txt
Remove codecov. We aren't using it and they had a security breach
> MNT: remove codecov following security breach

- .travis.yml
- docs/source/client.rst
What the title says. Also changed the allow failure name to match pcdshub/pcds-ci-helpers#65
Fixes #224  
Built docs locally, hoping Travis approves as well.
Nowhere.
> BUG: Fix ambiguous cross-reference to Client

- docs/source/releases.rst
Release notes for this tag
Probably should have done this tag sooner
> DOC: add release notes for v1.10.0

- docs/source/releases.rst
> DOC: add release notes for v1.10.1

- docs/source/releases.rst
Add release notes for @klauer's recent PRs
I want to make a tag
> DOC: add release notes for v1.12.0

- docs/source/conf.py
- happi/cli.py
- happi/tests/test_cli.py
- add glob/regex flag, and related documentation
- fix numeric handling 
- fix range_search logic.  (Previously would only consider last range query, will now properly consider many ranges)
- adds / modifies test cases to better cover search behavior (search range intersections, exit codes, regex vs glob, etc)
- If input is invalid we exit with exit code 1 via `click.Abort()` (bad search range).  If search simply fails to return anything, the program was successful.  
- Various logic modifications to make the diff annoying
#250 , but a more careful look is ongoing
Interactively, and tests to come
This PR.
> ENH: search cli enhancements / refactor

- docs/source/releases.rst
> DOC: write release notes for v1.13.0

- happi/__init__.py
- happi/containers.py
- happi/device.py
This reverts commit 5922b25a29b6baf2c61b34cfb502d78baa4da0e5.
* As discussed in #273.
* Release notes will be tweaked in that PR post-merge.
* `Device` removal should not happen before v2.0.0
* Revert it for the v1.14.0 tag
Test suite
> Revert "CLN: remove happi.Device; pairs with pcdsdevices PR 1023"

- docs/source/releases.rst
Missed a change in the release notes.
Did I/we miss any others before we finalize this with a tag?
> DOC: JSON file location relative to config

- .github/workflows/standard.yml
- conda-recipe/meta.yaml
- dev-requirements.txt
- docs/source/upcoming_release_notes/331-pcds-libraries-requirement.rst
Add pcdsdevices and pcdsutils to dev requirements and conda recipe, and remove it from the github actions extra testing-specific requirements. 
The libraries should be considered required instead of optional for testing.
Closes #331 
inspired by #329 
Test suite runs, github actions workflow and fresh environment building completes as expected.
Here, and the aforementioned issues.
> Import changes for pcdsutils and pcdsdevices

- .github/CODEOWNERS
- .pre-commit-config.yaml
(autogenerated) adding codeowners file
> MNT: Adding CODEOWNERS file
