pcdshub/happi

happi/containers.py
Changed to match the pcdsdevices naming convention. Also data should be optional in the event that the prefix matches the `data` key
=> API: Change Mirror to OffsetMirror

happi/device.py
Switch info to debug, use module logger instead of root logger.
Largely a selfish PR, this log message spams me while loading devices in skywalker.
=> LOG: Small fix

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .travis.yml, conda-recipe/meta.yaml, happi/client.py, happi/device.py, happi/loader.py, happi/tests/test_loader.py, happi/utils.py, requirements.txt
Devices now have the following standard pieces of EntryInfo: `device_class`, `args` and `kwargs`. This divorces us from the model of a one to one mapping of `happi.Containers` to `pcdsdevices`. It also allows the addition of initialization arguments without adding EntryInfo or changing classes. By default, the `args` and `kwargs` default to the standard `ophyd.Device` (prefix, name=name) loading scheme.
Because we don't want to duplicate information in the `args` and `kwargs` that is contained in other EntryInfo. I added a function that will render `jinja2` templates with a devices specific attributes. That means for instance the defaults args are will be `"{{prefix}}"`
The awkward thing about this setup is you still want to enforce a non-string type. We need to render the template, then …
=> ENH: Device loading

happi/containers.py
Update containers to load proper `pcdsdevices` classes. This way we know which are the required EntryInfo parameters, and you do not have to repeatedly point all your added devices to the same locations in `pcdsdevices`.
This is a temporary fix until #36 has a solution.
Closes #27 
Did not add tests to avoid a`pcdsdevices` dependency.
=> MAINT: Update pcdsdevices Containers

happi/containers.py
* When you only copy the `kwargs` EntryInfo the `kwargs.default` dictionary still points to the original dictionary. For the other EntryInfo you don't notice because you make a new pointer when you set.
```python
system = copy(Device.system)
system.default = 'vacuum'
```
However, when you call `.update` or `__setitem__` this is not the case. Now all the kwargs copies are deepcopies.
* The IPM `device_class` was mis-spelled.
Tested on mfx config
=> Container Fix

happi/client.py, happi/loader.py
1. Was having trouble deciphering an exception in the happi Client. Added the `raise . from .` syntax to give a more descriptive traceback. I figured this should just go in the library permanently.
2. While writing tests for another module, I discovered that you can not use `load_devices` if one of your classes references metadata on load. This is because we try and enforce the type by looking up the EntryInfo, but there is no EntryInfo for metadata. This just wraps it in a try / except block and trusts that the given metadata is already the correct type.
=> Exception Details

happi/loader.py, happi/tests/test_loader.py
Attach metadata to objects after they are created by happi. This is wrapped in a `try / except` block  as some classes do not support `setattr` for new attributes. You can also choose not do attach the metadata at all with the `attach_md` kwarg.
Allows applications like `hutch_python` and `lightpath` to access metadata of the devices that may not be included in the class constructor i.e `my_device.md.z`
Added an additional test to check metadata addition
Update doc-string
=> Attach metadata

happi/backends/qs_db.py, happi/loader.py, happi/tests/conftest.py
* `QSBackend` passes kwargs to the QuestionnaireClient to allow multiple authentication methods
* Logging messages have been updated to match the MFX `dev` area changes
* Allow the use of `ws-auth` after https://github.com/slaclab/psdm_qs_cli/pull/2
=> Questionnaire Kwargs

happi/__init__.py, happi/loader.py, happi/tests/test_loader.py
Simplest implementation of device caching. Idea is to check if a device has already been created rather than creating a new one. Cache is available as `happi.cache`. If a user wants to force a new object to be created they can pass `use_cache=False` into `from_container`. This creates a new device and replaces it in the cache.
* This is currently just a regular dictionary. We can make it a `weakref` if we want to destroy devices when they go out of scope.
Closes #29 
Added a test where we compare  object memory addresses using  `id` 
Added a docstring in `from_container`.
=> ENH: Cache

happi/backends/qs_db.py
Prior to this devices with empty names and prefixes were loaded by the Questionnaire plugin. The code simply checked for the key, not that the key was an empty string. Now we:
* Check that both `name` and `prefix` are not empty strings
* Provide a much more descriptive warning message about which row in the table is bad.
Closes #44 
Tested on live Questionnaire with bad entries.
=> FIX: Do not load devices without names or prefixes

.travis.yml
Newer versions of `doctr` change the key name. This needs to be updated in Travis.
=> CI: Use correct key name in Travis

.travis.yml, dev-requirements.txt, happi/containers.py, happi/loader.py, happi/tests/test_loader.py
Found these two edge cases while populating the happi database with XRT devices:
* If there was an optional keyword mentioned in kwargs we would try and convert it to a NoneType. This was annoying in the case:
```python
MyDevice.prefix_det = None
MyDevice.kwargs = {"name": "{{name}}", "prefix_det": "{{prefix_det}}"}
```
* The `fill_template` raised an error if we tried to enforce_type on a already filled_template i.e `kwargs = {'a': 'b'}`
* In an older version of `lightpath` you had to pass in `destinations` to each branching device. This is no longer the case. I deprecated the Container type that required this as a piece of `EntryInfo`
* Add `flake8` tests to Travis
Tests are added for edge cases
=> FIX: Edge cases in templates

happi/backends/qs_db.py, happi/tests/test_backends.py
DO NOT MERGE UNTIL https://github.com/pcdshub/pcdsdevices/pull/167
When loading motors from the Questionnaire, guess which type each is by looking at the prefix. I view this is a temporary fix until the QuestionnaireClient can tell us explicitly which class should be loaded.
**Question:** Should the default be `pcdsdevices.epics_motor.PCDSMotorBase` or `ophyd.EpicsMotor`? Not sure ... My only thought is that our base version will work on true MotorRecord motors, but the `EpicsMotor` won't work with our bastards.
Without this fix Newport and PMC100 motors will not load properly from the Questionnaire. 
Added tests for both guessing the motor type, and that it works in situ.
=> ENH:Questionnaire Motor Guess

docs/source/index.rst, docs/source/releases.rst, happi/loader.py, happi/tests/test_loader.py
Prior to this `from_container` quietly grabbed devices from the cache if `use_cache` was True. This is confusing if you want to iterate on your container a few times before saving to the database.
```python
my_device.name = 'Unchanged Name'
my_device = from_container(my_container)
my_container.name = 'Changed Name'
my_device = from_container(my_container)
my_device.name == 'Unchanged Name'  # VERY CONFUSING
```
After #40 we can expect most of our objects to have the metadata they were loaded with attached as `md`. This PR adds a little check, if the `md` stored on the cached device is differing from incoming container, we force a reload, even if they share a prefix. This prevents the situation above. If the cached device does not have the `md` attached we just listen to whatever …
=> MAINT: Check metadata on Device before using cache

.travis.yml, docs/Makefile, docs/source/conf.py, docs/source/containers.rst, docs/source/develop.rst, docs/source/releases.rst, happi/__init__.py, happi/backends/qs_db.py, happi/client.py, happi/tests/conftest.py, happi/tests/test_client.py
We didn't have the top level import for loading a single device -> `from_container`.
I kind of realized that this should be a default method on `Client`. I think the main reason I didn't is because I couldn't think of  a name. Thoughts on?
`find_device` -> search and return `happi.Device`
`load_device` -> search and return `ophyd.Device`
I think the reason I didn't do this before is in `happi` < `1.0.0`, `load_device` **was** a function that returned a `happi.Device`. I renamed it to avoid future confusion. 
Closes #72
=> Discussion: Explicit import of from_container

happi/backends/__init__.py, happi/client.py, happi/tests/test_client.py
First whack at a persistent and simple way to setup a new `happi` client pointing to our deployed database. The basic issue is when I spawn a new process I don't want to have to keep track in a thousand different places the full path to the `JSON` file that contains my devices. This information will only get more complicated if we do things like: go to MongoDB, separate our single database into smaller hutch databases e.t.c
The solution I came up with is setting up a simple configuration file that looks like:
```ini
[DEFAULT]
backend=json
path=path/to/my/db.json
```
We then have an environment variable `HAPPI_DB` that points to the configuration file, and calling `happi.Client.from_config()` with no arguments will find this environment variable, load the configuration and return a …
=> Happi Configuration File

happi/device.py
Adds two new keywords:
**lightpath** - Easy key that makes it very transparent whether we should include this device in the LCLS Lightpath. I like this way better than keeping a big list of accepted classes. `active` always overrules this (i.e an inactive device with `ligthpath=True` will not be shown
**documentation** - Keeping this very ambiguous. Not sure what I really want it to look like in the end. It could be a string that points to a single url or a list of sources or a dictionary that has a keyword for each documenting source. This is also slightly awkward as what you probably want is to have this on a class basis, not a device? Maybe not? Not sure.. In any case it wouldn't be hard to write a little script:
```python
my_awesome_html ='www.wtf_is_wrong_with_this_motor.com'
for …
```
=> Additional Keywords

happi/backends/json_db.py, happi/tests/conftest.py, happi/tests/test_backends.py, happi/tests/test_client.py
* `fcntl` is not importable on Windows. We do not plan to support or test on Windows, but the package should at least be importable and there isn't a real fundamental reason that the `JSON` backend shouldn't work on any operating system. 
* The testing suite was kind of a mess. We were using fixtures improperly, calling them as regular functions. In `pytest>=4.0` this now explodes. This is now handled better, using a more elegant fixture pattern.
Attn. @tacaswell
=> Windows Import

.travis.yml, happi/tests/conftest.py
More experienced @teddyrendahl knows that this too complicated a testing setup. A `pytest` fixture that has a variable number of parameter based on what you can import. 
That being said this is the one-line fix to make sure our tests still run w/o `mongomock` installed. The main reason I don't want to make this a testing requirement is it has no CONDA package and don't think the effort of packaging it ourselves is worth the time.
Verified locally without `mongomock`
=> DEV: Ensure tests pass without mongomock

.gitignore, happi/loader.py, happi/tests/test_loader.py
Closes #66 
- `load_devices` has an option to create each device in a background thread
- `load_devices` has an option to call an arbitrary function on the loaded devices in the background thread, to be used to wait for connection, etc.
- This is needed before we transfer the camera load from `hutch-python` to `happi`
- This allows us to efficiently load devices that need PV gets to initialize that could time out
- This allows us to catch timeouts/disconnections early without sacrificing tons of time for applications like `lightpath`, but also give us flexibility to add checks in applications that need specific checks without thinking of all the possibilities in the `happi` module. It also helps stave off the "hidden" `ophyd` dependence by not assuming we only have `Device` and `Signal` …
=> ENH: Threads

examples/qt/treeview.py, happi/qt/model.py, happi/utils.py
Add a Happi-aware QTreeView that can display the results of a Happi search.
To allow UI projects to better leverage Happi in an uniform way.
This will be used for LUCID and other projects.
Locally via example shipped with this PR
Not yet documented.
There is this little detail demonstrated at the last piece of the GIF above in which if we filter and no child match the filter but the parent does, only the parent is displayed.
That is not a show stopper but in order to fix that we would need to subclass the QSortFilterProxyModel and tweak the `filterAcceptsRow` method. I'm not sure how much effort we should put into something like this. Up for discussion.
=> ENH: Happi-aware QTreeView

happi/backends/__init__.py, happi/client.py
I set out to further understand happi internals and ~close~ #24, but in writing the commits here, I think there may not be anything to fix.
The couple things here add a bit of clarity and also allow access to all loaded backends - which could potentially be an entrypoints hook at some point, I suppose. So, this doesn't have to be merged 🤷‍♂ 
I thought we were going to have a single database for beamline devices, at least. Other uses of happi (which do not yet exist) should load a different configuration that only they are aware of?
Perhaps @ZLLentz could further clarify and decide whether or not we can ~close~ #24.
=> MNT: Multi backend

happi/backends/json_db.py, happi/backends/mongo_db.py, happi/cli.py, happi/client.py, happi/tests/conftest.py, happi/tests/test_backends.py, happi/tests/test_cli.py, happi/tests/test_client.py
Working on getting full-match find alternatives such as:
* Find by regex
* Fuzzy find
Closes #4 
Hopes to address #98 eventually
Docstrings, not docs yet
I expect that different backends could support different search methods, requiring only `find` to be fully supported. 
I'm definitely open to suggestions as to how this should look.
=> ENH: happi.client.Client.search() refactor

happi/client.py, happi/tests/test_backends.py, happi/tests/test_client.py, happi/tests/test_device.py
Closes #55 
Separately, renames `Client._id` -> `Client._id_key` as the lack of description made it confusing.
=> FIX: Device add and save

docs/source/client.rst, docs/source/client_api.rst, docs/source/conf.py, happi/__init__.py, happi/client.py
Closes #123 
Partially address deprecation of `device`, as in #124 
Docs building locally successfully
=> DOC: Fix docs for searching

docs/source/conf.py, docs/source/containers.rst, docs/source/conventions.rst, docs/source/releases.rst
Docs were broken. This PR fixes the docs to build again and updates the release notes section using https://github.com/pcdshub/pcdsutils/issues/14#issuecomment-630360127 as a tool for it (Thanks, @klauer).
The `autosectionlabel` was a useless extension which was also causing issues with the release notes. I tracked down the instance in which it was being used and replaced it with a regular reference.
Closes #129
Locally
It is documentation.
=> DOC: Release Notes & other fixes

happi/client.py
Wrap the search results in try/except so that one failing device in an `all_devices` call doesn't explode the whole thing.
I'm not sure if this is the best way to fix the problem, but it is a way and it was quick to implement. Maybe this has other negative knock-on effects?
Currently, `typhos <happi-name>` does not work for any device because there is at least one device with a bad entry in lcls's happi config. (There are actually tons of bad entries, but this is irrelevant: https://github.com/pcdshub/device_config/issues/10)
`typhos` has a step where it gets all devices in the database. This fails with a long, confusing traceback about being unable to load the user's device, but this is actually a traceback about failing to load the first device listed in the happi config. This is …
=> MNT: don't error out if one of many devices has a bad entry

happi/client.py
```
(pcds)zlentz@psbuild-rhel7-01:~$ happi search st1k4
[2020-06-09 09:32:10] - WARNING -  Entry for st1k4 is malformed. Skipping.
[2020-06-09 09:32:10] - ERROR -  No devices found
(pcds)zlentz@psbuild-rhel7-01:~$ happi load st1k4
[2020-06-09 09:32:18] - INFO -  Creating shell with devices ['st1k4']
Traceback (most recent call last):
File "/reg/g/pcds/pyps/apps/dev/pythonpath/happi/client.py", line 272, in find_device
device = self.create_device(doc['type'], **doc)
File "/reg/g/pcds/pyps/apps/dev/pythonpath/happi/client.py", line 207, in create_device
if not issubclass(device_cls, HappiItem):
File "/reg/g/pcds/pyps/conda/py36/envs/dev/lib/python3.6/abc.py", line 228, in __subclasscheck__
if issubclass(subclass, scls):
File "/reg/g/pcds/pyps/conda/py36/envs/dev/lib/python3.6/abc.py", line …
```
=> FIX: device_cls string leaking through raising bad exception

happi/cli.py
- I modified `/happi/cli.py` to try to `getattr` when parsing the `edit` argument before setting the object's attribute. If this fails, it logs and error message about the field that was not successfully set. 
- If we try to set any invalid fields, then we exit the process 
We want to warn the users when they are trying to edit a non-existing field for a device
We also want to exit the process if any invalid information is detected to keep the integrity of the database 
trying to close #147 
This has been tested with a dummy db.json file 
Test with two fields that fail and one that succeeds: 
`happi edit my_name_here beamline=my_beamline stand=my_stand prefix=my_prefix`
Test with single field that succeeds:
`happi edit my_name_here prefix=my_prefix`
Nowhere
=> FIX: fix silent fail when editing a nonexisting field

dev-requirements.txt, docs/source/cli.rst, docs/source/conf.py, docs/source/index.rst, happi/cli.py
- I have added a new .rst file under the `/docs/source/` folder called `cli.rst` that uses the **argparse** directive `..argparse::` which automagically generates the documentation for the command line arguments
- I have added a new dependency: `sphinx-argparse` in `dev-requirements` 
- Enabled the extension `sphinxarg.ext` in the sphinx config file
- Changed cli.py file so that we have a function that returns the parser (needed for the `..argparse::` directive) - just encapsulated the parser's lines from `cli.py` into a function called `get_parser`
We need to provide users with documentation about Happi's Command Line Utilities
closes #135 
```
cd docs
make html
firefox build/html/index.html
```
This generates the HTML documentation for HAPPI at the `/docs/build/html` folder. 
Locate the …
=> DOC: Add documentation for cli

examples/db.json, examples/qt/listview.py, examples/qt/treeview.py, happi/qt/model.py, happi/utils.py
- Have removed the previous two devices from `happi/examples/db.json` and added two `OphydItem` items instead (they are using the same names and prefixes as the previous ones)
- Have changed the `happi/happi/qt/model.py` to pass in `entry.item` instead of `entry` when creating an item, and when using the `get_happi_entry_value` function
The example had to be reworked to use OphydItem instead and be standalone.
closes #150 
Check to see if it validates:
```
>>> client = happi.Client(path='./examples/db.json')
>>> client.validate()
[]
```
Run the `listview.py` and `treeview.py` widgets to see the items
This has not been documented
=> MNT - change db.json examples to use OphydItem 

happi/backends/json_db.py, happi/cli.py, happi/tests/test_cli.py, happi/utils.py
- ` happi search` command line has been modified to use `search_regex` and `search_range` (for z values) instead of the previous `search` function. 
- this change will allow the user to search using the asterisk symbol `*` that matches 0 or more occurrences.
ex: `*kmono*` will match any occurances that have `kmono` in them
- this also allows the user to search for a range of `z` values by typing a valid range separated by comma like so:
- z=0,89
**Note:** there is no space between the values
Intended to close #141 
Will possible close #144 as well
Has only been tested locally with items from a dummy json database. 
**Has Not been tested with a mongo database!!** 
**Ex:**
- `happi search z=1,5`
```+--------------------+-------------------------------------+
| EntryInfo          | Value …
```
=> Cli search regex

happi/cli.py
It turns out there was just a simple typo when calling a function from `HappiRegistry`. It might have been that the function itself was changed after the clone was added, maybe not... 
So this PR fixed this typo and now the `clone` command seems to work fine. 
This change was necessary to make the `clone` command work. 
Trying to close #156 
Has been tested locally with a dummy json database: 
Trying cloning **`an_item`**:
```
happi add --clone an_item
[2020-08-19 09:45:36] - INFO -  Enter value for name, default=an_item, enforce=re.compile('[a-z][a-z\\_0-9]{2,78}$')
an_item_2
[2020-08-19 09:45:45] - INFO -  Enter value for device_class, default=class, enforce=<class 'str'>
[2020-08-19 09:45:48] - INFO -  Selecting default value class
[2020-08-19 09:45:48] - INFO -  Enter value for args, …
```
=> FIX: fix typo in cli.py for clone command

happi/cli.py
Using `len(sys.argv)` to count the arguments passed to happi, and printing the happi usage if only one argument is passed
This change allows the user to see what commands are available when only `happi` is typed without any sub commands. 
Trying to close #154 
This has been tested locally only: 
```
(python3.7) $ happi
usage: happi [-h] [--path PATH] [--verbose] [--version]
{search,add,edit,load} ...
```
N/A
=> ENH: Output usage without subcommands

happi/client.py
Add exception message to warning when entry is malformed.
While trying to learn happi.loader, the terse message did not inform what, exactly, was wrong.  With the exception text, learned that `name` attribute (in JSON file) must be at least three characters and must not have uppercase.
with
```json
{
"m1": {
"active": true,
"documentation": null,
"args": [
"{{prefix}}"
],
"kwargs": {
"name": "{{name}}"
},
"type": "OphydItem",
"_id": "pinhole",
"device_class": "ophyd.EpicsMotor",
"name": "sky_M1",
"prefix": "sky:m1"
}
}
```
shows
```
WARNING:happi.client:Entry for sky_M1 is malformed (name='sky_M1' did not match the enforced pattern[a-z][a-z\_0-9]{2,78}$). Skipping.
```
see proposed changes
=> When malformed, make warning more informative

conda-recipe/activate.sh, conda-recipe/build.sh, conda-recipe/deactivate.sh, happi/cli.py, happi/tests/test_cli.py
* Adds `happi search --json` option to output JSON instead of a table.
* Moves IPython import to where it's needed, saving approximately half a second on any other `happi` CLI invocation
* Adds activate/deactivate scripts which can be used in conjunction with a fuzzy finder called `fzf`
Old video from issue #98: https://asciinema.org/a/358799
The video shows the underlying mechanism but not the (relatively) user-friendly option that this PR provides:
with this PR, you type `happi search **[TAB]` and it'll show that same filterable list of names.
* Names are difficult to type and remember, even with globs
* Locally and manually
=> ENH: bash/fzf-based fuzzy finding of happi items

.pre-commit-config.yaml, happi/backends/qs_db.py, happi/client.py, happi/tests/conftest.py, happi/tests/test_backends.py
* Add a questionnaire helper class to:
1. Break up loading routine into more maintainable functions
2. Allow for introspection of state
Closes #175 
* Locally, but I'm hoping to add more tests
* Looking for an experiment that has valid entries for better testing, too
```python
In [1]: import happi
from happi.backends.qs_db import QSBackend
qs = QSBackend('xcsx41018', use_kerberos=True)
In [2]: qs.helper
Out[2]: <QuestionnaireHelper experiment=xcsx41018 run_number=run18 proposal=X410 beamline=XCS>
```
=> Questionnaire cleanup

happi/client.py
Mistakenly left in a `raise` I had used during testing to determine why questionnaire items weren't being loaded.
Only just noticed after comparing the releases (sorry, @ZLLentz )
=> FIX: erroneously left in `raise` for testing purposes

happi/backends/json_db.py
Pass jsondb path through `os.path.expanduser` .
I expect the following cfg file to work:
```ini
[DEFAULT]
path = ~/.local/share/happi/db.json
```
Currently it does not, happi requires FULL path.
Tested locally.
Not documented.
=> FIX: expand home directory (~) in JSON backend database path

happi/cli.py, happi/tests/test_cli.py
Add new CLI sytntax: `happi update <json>`. User supplies a JSON payload defining Happi items. Items from payload are verified then splatted into the database. In the case of an `_id` conflict, the NEW item is preferred and the old item is overwritten. Name is inspired by Python's `dict.update` method.
Closes #190.
This syntax allows for bulk management of the Happi database through easy integration with other command line tools. I am simultaneously updating yaqd to introduce Happi-formatted output, see [GitLab MR](https://gitlab.com/yaq/yaqd-control/-/merge_requests/42).
It is my hope that this interface will allow for other device-discovery tools to easily add Happi support.
Tested locally. All of the following work on my machine.
```bash
$ yaqd list -f happi | happi update
$ happi …
```
=> happi update <json>

happi/item.py, happi/tests/test_device.py
Add a special case for boolean entry enforcement where we interpret the input string instead of just casting it into a boolean.
Accepts strings like "true" and "false" as stand-ins for `True` and `False` in situations where the input must be given as a string, such as in the cli.
`happi edit` and `happi add` do not set boolean values as one would expect
closes #187
Added tests
Will include in release notes, I'm going to count this as a bugfix.
=> MNT: fix confusing behavior with boolean enforcement

docs/source/containers.rst, happi/item.py, happi/utils.py
- Remove the requirement for names to be between 3 and 80 characters
- Keep requirement for names to be valid Python identifiers
- Add previously implicit requirement for names to not conflict with reserved keywords
- Add feature to use arbitrary functions as enforce parameters
This is a site-specific assumption that should not be baked in to the base class
closes #206 
~Online regex tester site to quickly vet python identifier~
The above is no longer valid, since we are no longer using regex here.
But I think this is fine since the existing tests still pass and we're using core python built-ins to validate the names, rather than custom regex.
Added some to the docs folder
Will be in the release notes
=> ENH: allow short and long names

happi/cli.py
Adding new command to CLI.
```
$ happi container-registry
+------------------------------------+------------------------------------+-------------------------------+
| Container Name                     | Container Class                    | Object Class                  |
+------------------------------------+------------------------------------+-------------------------------+
| Device                             | happi.device.Device                | None                          |
| OphydItem                          | happi.item.OphydItem               | None                          |
| HappiItem                          | happi.item.HappiItem               | None                          |
| bluesky_autonomic._happi.DelayItem | bluesky_autonomic._happi.DelayItem | …
```
=> ENH: add command to display container registry

happi/cli.py
Enable new flag to `happi search`, `--names`.
```bash
$ happi search "*"
(pretty table)
& happi search "*" --names
d1 d2 mysensor
```
If both `--json` and `--names` are provided the output is json.
Feel free to reject or ask for major changes.
Motivated by #231, I can now do this:
```bash
$ happi load "$(happi search "*" --names)"
[2021-12-22 12:04:39] - INFO -  Creating shell with devices ['d1 d2 mysensor']
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: d1
Out[1]: <yaqc_bluesky._device.YAQDevice at 0x7f41ed902f10>
```
I had to massage `load` a little bit to do this, but not in a way that changes existing behavior.
I don't …
=> ENH: cli search flag to output names

happi/backends/json_db.py
Missing keys should not cause a find match to fail.
Investigating xcs long load times
```
2022-03-03 16:44:27 - PID 7917         json_db.py: 149 _iterative_compare DEBUG    - Comparison method failed: 'lightpath'
Traceback (most recent call last):
File "/u1/xcsopr/conda_envs/pcds-5.2.1/lib/python3.9/site-packages/happi/backends/json_db.py", line 146, in _iterative_compare
if comparison(name, doc):
File "/u1/xcsopr/conda_envs/pcds-5.2.1/lib/python3.9/site-packages/happi/backends/json_db.py", line 190, in comparison
if all(value == doc[k] for k, value in to_match.items()):
File "/u1/xcsopr/conda_envs/pcds-5.2.1/lib/python3.9/site-packages/happi/backends/json_db.py", line 190, in <genexpr>
if all(value == doc[k] for k, value in to_match.items()):
KeyError: 'lightpath'
```
=> FIX: missing keys should not cause failure in backend

.pre-commit-config.yaml, happi/loader.py, happi/tests/test_loader.py
* Only affects those using `load_device` or `load_devices`, which are CLI-facing wrappers around `load_container` (used by `client[device].get()`
* Are there any users outside of SLAC for this?
* Cleans and annotates `happi.loader`
* Some warning messages were made more descriptive
* Consolidated message printing logic
* Bonus: updates old pre-commit settings
* Some devices take a long time to load, it would be nice to know which without digging too much
* hutch-python loading and test suite
This PR text
=> ENH: optional per-device load times

happi/backends/json_db.py
* Reduce on-import warning of fcntl to debug.
* This is shown repeatedly on Windows for ads-deploy - which doesn't even really use happi - and is a bit annoying.
Closes #220 
If it passes flake8 and imports, this should be fine.
Issue / PR text
=> MNT: switch fcntl warning to debug

docs/source/containers.rst, happi/item.py, happi/tests/test_device.py
- Adds `enforce_doc` kwarg to EntryInfo for more informative exceptions on enforcement failure
- updates some docs to make this more visible.
- added some assertions in tests to make sure this is visible
closes #217 
Interactively, tests have been updated
Documentation has been updated
=> ENH: add enforce_doc kwarg to EntryInfo

happi/tests/conftest.py, happi/tests/test_backends.py
- uses tempfile.NamedTemporaryFile instead of writing a .json file and cleaning it up (in conftest.py and test_backends.py)
closes #216 
There are still portions where json is created, but the writing of those files seems to be the target of the test, so I've left those alone
Tests run and no json is left behind.  
This PR
=> TST: use tempfile for mockjsonclient fixture

.travis.yml, dev-requirements.txt, docs/source/cli.rst, docs/source/conf.py, happi/__main__.py, happi/cli.py, happi/errors.py, happi/item.py, happi/prompt.py, happi/tests/test_cli.py, happi/utils.py, setup.py
A rather long PR, which initially started as an effort to simplify our cli code base using `click`, but started to tackle broken/missing functionality along the way.  An effort has been made to preserve existing functionality, except where existing functionality was broken.  
- Refactors happi_cli into a click command group, with subcommands (search, add, etc)
- Reworks tests to use click.testing.CliRunner, which keeps track of exit code, exception, and stdout/stderr
- Adds various helpers along the way
- Enforce values received in `happi edit`, and properly handle dicts/lists
- Fixes user-input dictionaries and lists to actually work (issue here?)
The CLI interface has needed some touching up, particularly in the user-prompting side of things.  Users often edit the json directly, and …
=> ENH: Refactor happi cli to use click instead of argparse

docs/pre-release-notes.sh, docs/release_notes.py, docs/source/conf.py, docs/source/index.rst, docs/source/upcoming_changes.rst, docs/source/upcoming_release_notes/253-fix_tests.rst, docs/source/upcoming_release_notes/template-full.rst, docs/source/upcoming_release_notes/template-short.rst, happi/tests/conftest.py, happi/tests/test_backends.py, happi/tests/test_cli.py, happi/tests/test_client.py, happi/tests/test_device.py, happi/tests/test_loader.py, happi/tests/test_prompt.py
- Fixes deprecation warnings for `happi.device.Device`.  Remaining warnings are from other libraries (pcdsdevices defines containers with `happi.device.Device`, other unrelated warnings)
- Type annotations for test fixtures
- Split `three_valve` fixture into `three_valve` (containing valve info) and `client_with_three_valves` to avoid confusion over fixture side effects
- add pre-release notes templates
#253 , and I was tired of seeing the same warnings.  I reworked a bunch of cli tests in the search-refactor PR as well
We test the tests via local pytest and automated ci tests
this PR
old:
new:
=> TST/MNT: Fix tests, add pre-release notes

.gitignore, .travis.yml, happi/cli.py, happi/tests/conftest.py, happi/tests/test_backends.py, happi/tests/test_cli.py, run_tests.py
I'm on a quest to improve the loading performance of our specific ophyd devices at LCLS. I want to build these tools into `happi` so that it becomes easy to identify when an arbitrary device is taking a long time to load.
Interactively + some basic argument tests to make sure the benchmark and profile can at least complete.
N/A
=> ENH: Benchmark, Profiling

.flake8, docs/release_notes.py, docs/source/upcoming_release_notes/235-performance.rst, happi/backends/core.py, happi/backends/json_db.py, happi/backends/qs_db.py, happi/client.py, happi/tests/test_client.py
* Adds cache clearing mechanism to backends
* Each call to `client.search()` (and such) will hit the database once and cache internally
* User of client can further indicate that caching is to be done by way of the `retain_cache_context`
* Noted an additional performance issue: 
* Search methods retrieve entire documents
* When the client tries to instantiate a `HappiItem`, it hits the database again with just the identifier, retrieving the same document prior to instantiation
* This is where the `_get_item_from_document` refactor comes in
Addresses #235
Solely the test suite
Issue and PR
=> REF/PERF: caching mechanism for happi Client and backend databases

docs/source/upcoming_release_notes/267-use-search-cache.rst, happi/cli.py
Small follow-up to #265 
Here we force the search to use one cache for entire search (if applicable based on the backend).
- Slightly more efficient: these searches will read the file exactly once instead of 1, 2, or 3ish times (or more with some inputs)
- Avoid issues with the database updating during a search and getting conflicting search results
Interactively with:
```
$ happi profile --database z=0,1000 im1l1
```
And seeing the json reads drop from 2 to 1.
I need to run the pre-release thing
=> ENH: use one cache for the entire cli search block

happi/cli.py, happi/containers.py
* Load the happi container registry on the first access and not on import
* Add documentation about the registry
* Add type hints for the registry
* Add a companion `__setitem__` for the ability to externally add items to the container registry.
* That is, `registry[name] = ContainerClass`
* Fixes scenario where a module including a happi container also attempts to import from happi (as @tangkong found)
* We don't really have a test suite for the registry
* It's tested implicitly through the client/CLI tests
This PR text.
=> REF/FIX: more lazily load the happi container registry

.github/PULL_REQUEST_TEMPLATE.md, docs/pre-release-notes.sh, docs/source/upcoming_release_notes/270-lazy-registry.rst
* Add missing pre-release notes from #270 
* Updated pre-release tool (synchronized with pcdsdevices)
* Updated pull request template to include a pre-merge checklist (from pcdsdevices)
* I forget which repositories have pre-release notes.  
* The checklist is good for us and contributors.
`$ make html` works
=> DOC: container registry + update pre-release note tooling

docs/source/upcoming_release_notes/278-Improve_error_handling_and_logging_in_the_happi_cli.rst, happi/cli.py, happi/tests/test_cli.py
Improve some of the error handling and logging in happi CLI.
Error handling was previously a combination of `click.Abort()`, `print` and `logger.XXX` functions for the CLI interface. This PR consolidates this handling into `raise click.ClickException(message)` where applicable. Most of the instances changed here were related to user input validation, which probably doesn't need to be logged with the "proper" logging interface in the first place.
There were also a couple instances where an exception was unhandled, this PR fixes those too.
Originally I was only going to address the unhanded exceptions here, but I decided that it might be good to consolidate the logging for CLI and make it more consistent. This improves the overall "user experience" for the command line, as exceptions are …
=> ENH: Improve error handling and logging for happi CLI

docs/source/upcoming_release_notes/282-enh_filter_default_kwargs.rst, happi/item.py, happi/loader.py, happi/tests/conftest.py, happi/tests/test_cli.py, happi/tests/test_loader.py
- Adds the kwarg `include_default_as_kwarg` to `EntryInfo`
- Adds a clause in `from_container` to omit `kwargs` if their value is equal to the default stored on the corresponding `EntryInfo`, triggered by the `item._info_attrs['kwargs'].include_default_as_kwarg` flag.
- Gives individual `EntryInfo`'s the ability to decide whether or not to `include_default_as_kwarg` in the case where `item._info_attrs['kwargs'].include_default_as_kwarg = True`
- adds tests for this feature and a fixture that covers jinja template code paths
What is the behavior now?  Considering the case where we are attmpting to load a device from the following document:
```yaml
{
'name': 'alias',
...
'kwargs': {
'hi': 'oh hello',
'blank': '{{blank}}'
},
'blank': 'default_blank'
}
```
- `'hi' = 'oh hello'` will always be …
=> ENH: allow filtering of kwargs that have a value matching the default

docs/source/upcoming_release_notes/284-mnt_max_table_width.rst, happi/item.py
Calculates a max width for tables generated by `item.show_info()` based on the current terminal width
After I added a bunch of kwargs, the tables got annoying to view.  
Interactively
This PR.
Before
After
=> MNT: set a max width for item.show_info tables

docs/source/upcoming_release_notes/287-enh_multi_backend.rst, happi/backends/__init__.py, happi/backends/core.py, happi/backends/json_db.py, happi/backends/mongo_db.py, happi/backends/multi_db.py, happi/client.py, happi/tests/test_backends.py
- Creates MultiBackend, which itself takes multiple backends.
- MultiBackend prioritizes backends in the order they are listed in the config, with the DEFAULT config used last
closes #24 ... some things never change
If users have small, hutch-specific configuration changes to the happi database, previously they would have to direct happi to their own version of the database.  This allows users to incorporate a small db file on top of our facility-wide device_config, which acts as a fallback.
Currently our config files have only the path to a single db file, with the option to specify a backend and its associated initialization arguments
```
[DEFAULT]
path = /cds/home/r/path/to/db.json
```
This PR allows sections other than `DEFAULT` to specify additional backends.   If more than one …
=> ENH: Simultaneous Multi-Backend support

.travis.yml, docs/source/upcoming_release_notes/294-enh_delete_copy.rst, happi/cli.py, happi/tests/conftest.py, happi/tests/test_cli.py
Adds a delete cli command.  Touches up some of the `add --clone` documentation to hopefully make it more obvious you can copy items. 
Modified existing test db to have `_id` match `name`, because happi was getting confused.  (happi client assumes `_id_key = name`)
I was asked about this twice in one week, meaning it was time to make it easier for people
closes #293 
Added a delete test.  Looked at the `happi -h` output
This PR, docstrings
=> ENH: add delete cli command

docs/source/upcoming_release_notes/295-enh_audit_fns.rst, happi/audit.py, happi/cli.py, happi/tests/conftest.py, happi/tests/test_audit.py
Adds additional audit functions for:
* ensuring any jinja-filled args or kwargs have corresponding entries
* checking that all signals in a device are connected
These got prototyped during some debugging and I figured it was a good time to push this forward
The args and kwargs test needs to pull the document from the client directly, since when a HappiItem is created, any fields that exist on the container but not in the document are filled with `None`
closes #290 
A test case for the args/kwargs audit has been added.  (this took the bulk of the time, the tests were finicky)
This PR
=> ENH: add audit functions - arg/kwarg information verification and wait for connection

docs/source/upcoming_release_notes/300-enh_repair.rst, happi/audit.py, happi/cli.py, happi/tests/conftest.py, happi/tests/test_audit.py
Adds the `happi repair` command, which (currently) aims to update the database to align with the information expected by the container
Some attempts are made to cancel the saving process safely, as well as prompt the user for missing information
#297 , where initial search failures were tracked down 
A short list of cases I tried to cover / thought about:
|                      | Mandatory             | Optional                |
|----------------------|-----------------------|-------------------------|
| Missing, has default | not possible       | fill with default value |
| Missing, no default  | prompt                | fill with 'null'        |
Currently if you run the audit and there are no mandatory items with missing data, the procedure will just re-save the item.  I wanted to only …
=> ENH: `happi repair`

.github/PULL_REQUEST_TEMPLATE.md, README.md, docs/source/upcoming_release_notes/301-fix_save_corrupt.rst, happi/backends/json_db.py, happi/tests/test_backends.py
Use the operating system's copy/rename/move mechanisms to implement atomic updates of the json backend.
Accordingly, the file locking has been removed, it should no longer be necessary.
Also remove some references to Travis CI that I noticed while filling in the template.
closes #301 
Summary: if you press ctrl+c at the wrong time you can truncate your database if it uses the json backend.
I added some unit tests and the old tests still pass.
Interactively with a test db, I am able to ctrl+c and see my temp file be partially created without corrupting the main data file.
I want to make a more direct unit test that gives me a high confidence that interrupting this function at any time won't corrupt the database, but I haven't figured out a good way to interrupt the function at specific …
=> FIX: json backend atomic writes

pyproject.toml
* PyPI uploads broken since content type not set on long description (README)
* This sets the content type
PyPI release day
Ref: https://github.com/pcdshub/pcds-python-migration-tools/issues/17
Fingers crossing
=> BLD: set content type for readme

.github/workflows/standard.yml
Inherit secrets so we can publish to PyPI in our GHA CI workflow
=> CI: inherit secrets

docs/source/upcoming_release_notes/308-enh_post_md-hook.rst, happi/loader.py, happi/tests/test_loader.py
Adds a hook to allow code to be run on the object after the `.md` attribute is set.  This would allow the loaded object to interact with its metadata. 
Most recently https://github.com/pcdshub/pcdsdevices/pull/1132/, but also the lightpath input/output branches setting in pcdsdevices previously [(link)](https://github.com/pcdshub/pcdsdevices/blob/02b295e236a21b4d8fcdc6969041f5b8a3b5fa03/pcdsdevices/interface.py#L1787)
Previously, we've hooked the `.md` setter to do some operations after happi attempts to set  the `.md` attribute.  This has caused (me) confusion, and unless thoroughly annotated the purpose of the setter is not clear (mostly to me with  my goldfish memory)
Added a quick test 
Here, and pre-release notes eventually
=> ENH: add post-md-set hook to loader

docs/source/upcoming_release_notes/310-mnt_missing_key.rst, happi/qt/model.py
* Instead of omitting items, show them under a catch-all tree item "[KEY NOT FOUND]"
If you're looking to group items by a metadata key, I think you'd expect every item in the database to be represented.  If you were to group the database by a field and then search for an item, it might just not exist if its metadata didn't feature that field.
In reality this was inspired by the logger spam when switching between views.  Currently ATEF is the only real user of this model view, I think this is a better way to handle missing metadata.  
Sidebar: I considered modifying `get_happi_entry_value` to pass null/None values from the database through, but in the end this can be grouped together with missing keys without loss of information.  I do think raising a ValueError there is a bit overkill, …
=> GUI/MNT: let HappiDeviceTreeView include items where key is not found

happi/backends/json_db.py
Fix a 6-year-old typo in this docstring.
The docstrings are used to build the deployed docs, and typos in parameters can be especially confusing.
N/A
N/A
I'll do the documentation step later I just want to get the edit in now before I forget
=> DOC: fix old typo in parameters

docs/source/upcoming_release_notes/313-new_cli_command_edit-config.rst, happi/cli.py
Adds new command-line syntax `happi edit-config`, which opens the config file in `$EDITOR`. This way people don't have to remember or care where the config file is. On Windows falls back to notepad, elsewise vi. 
In conjunction with #312, I'm trying to make happi more end-user friendly, especially on Windows and non-managed machines. I personally like this pattern and yaq users are used to "... edit-config".
Works on my machine :smile:. If y'all want tests let me know.
Click's magic means it shows up under `happi --help`
=> ENH: add new cli command edit-config

docs/source/upcoming_release_notes/315-happi_config_cli_sub-commands.rst, happi/cli.py, happi/tests/test_cli.py, pyproject.toml
Adding new sub-command-group `config` to CLI.
- `happi config edit` - open config file in $EDITOR
- `happi config init` - create new config file with default options
- `happi config show` - show location & contents of config file
See #314 
Tested on my machine.
CLI is auto-documented.
=> ENH: happi config cli sub-commands

docs/source/upcoming_release_notes/320-bug_update_json.rst, happi/cli.py, happi/tests/test_cli.py
* Slightly modifies the `happi update` command to handle json formatted similar to a valid json database.
* Updates the `happi update` docstring (and by proxy help text) to better describe the use case
Now `happi update` can take JSON input that looks like a working json backend: 
<details><summary>Details</summary>
<p>
```
{
"al1k2": {
"_id": "al1k2",
"active": true,
"args": [
"{{prefix}}"
],
<...>
"type": "pcdsdevices.happi.containers.LCLSItem",
"z": 778.833
}
}
```
</p>
</details> 
or a list of items  in json form (original functionality):
<details><summary>Details</summary>
<p>
```
[{
"_id": "al1k2",
"active": true,
"args": [
"{{prefix}}"
],
<...>
"type": "pcdsdevices.happi.containers.LCLSItem",
"z": 778.833
}]
```
</p>
</details> 
Usage is now described in the subcommand.  One can …
=> MNT/DOC: parse valid json db, improve docstring

docs/source/upcoming_release_notes/322-happi-audit-split.rst, happi/audit.py, happi/cli.py
* Allow for running happi audits programmatically without interfacing with `click`
* Add some more type hints
* Intercept `KeyboardInterrupt` and still show some results in `happi audit` (when you're working from a laptop that has access to zero PVs)
Touching back on auto-generated documentation pages:
* I want to include happi audit information in the Confluence pages for each device and there's no really easy way to do this currently
Test suite and interactively
This PR
=> REF: split out happi audit for programmatic usage

conda-recipe/meta.yaml, dev-requirements.txt, happi/cli.py, happi/tests/test_cli.py
* Attempt to use selectors in requirements/conda recipe to let Python 3.11 be special in its line-profiler requirement
* Run profiler test suite on Python 3.9 and 3.10
* Avoid profiler test suite on Python 3.11
* Line profiler is too slow to work with our profiling code
* Line-profiler 4.1.0 is required for Python 3.11 to be functional
* Line profiler < 4 continues to work well for Python 3.9 and 3.10
* We can get Python 3.11 working *and* have Python 3.9, 3.10 still have its profiling tests by way of splitting the requirements into per-version requirements
CI and a bit of local testing / head-scratching
Entirely in this PR
=> BLD: test line profiler requirements fix / workaround

docs/source/upcoming_release_notes/302-repair_match_name_to_id.rst, happi/cli.py, happi/tests/test_cli.py
When running happy repair, will check if name and id fields are matching. If not, will set the name field to the id field. 
Added comparison and attribute setting in repair function. Added click context-based unit test for setting name and id equivalence. 
Changed 'res_name' variable to 'res_id' to represent correct value.
Closes #302 
Unit test using click contexts that call repair on the bad-happi-config.
Here
=> ENH: Match Name to ID Field 

docs/source/upcoming_release_notes/329-remove-extra-pcdsutils-import.rst, happi/tests/test_cli.py
Removed an extra pcdsutils import from test_cli.py that is outside of the try/except block with the other pcdsutils imports. 
Pytest will fail if pcdsutils is not installed in the environment. It appears to be imported in a later try/except block.
Pcdsutils also doesn't appear in any of the requirements files other than the workflows/standards.yml file. I haven't done anything about this, but felt that I should mention it. 
If we need another import within the try/except I'm happy to add it, or if I should add it in the requirements somewhere. 
Ran the pytest suite(after installing the up to date version of line-profiler(4.1.x) and pcdsutils) all tests pass 
Just this PR.
=> BUG: remove extra pcdsutils import

conda-recipe/meta.yaml, dev-requirements.txt, docs/source/upcoming_release_notes/333-doc_bson_not_req.rst, happi/backends/mongo_db.py
Documents `bson`'s presence in requirement files, and also adds a more descriptive ImportError in the one place we use it
#325 
N/A, but CI should cover it
this pr
=> DOC: explain bson dependency to avoid confusion

docs/source/upcoming_release_notes/304-remove_temporary_file.rst, happi/backends/json_db.py, happi/tests/test_backends.py
Closes #304  
If an error causes the temporary file in the json backend to not get copied properly, it would previously remain in the directory. It has not been needed so it will now be removed if left behind. 
In addition, because this file is no longer needed, the datetime and username are no longer needed in the file name. It is now just the unique hash to prevent collisions. Imports previously used to add time and username are now removed from the file.
Interactively, and a new test in test-backends.py 
Issues #303, #304
Comments within function itself and test.
=> Remove temporary file in JSON backend store function

docs/source/upcoming_release_notes/335-bug_xfer_default.rst, happi/prompt.py, happi/tests/conftest.py, happi/tests/test_cli.py
Fix happi transfer default handling (don't past default help text)
adds a test to try and cover this 
Also fixes `conftest.trim_split_output` because it just.. entirely didn't work.  More shame
In a burst of extra effort, disables assertion checks against expected stdout-style output.  The check still takes place, but simply prints (visible with `pytest -s` flag) if a mismatch is found.  In place of this, the happi_cfg is checked to verify the requested action has actually taken place.
Tests modified are:
- `test_transfer_cli`
- `test_transfer_cli_more`
- `test_search_json`  (this one is comparing to json, so I still assert the stdout comparisons here)
- `test_add_cli`
- `test_add_clone`
closes #334 , in part (the non-list / dict comprehension parts)
Adds a test
This PR
=> BUG: fix happi transfer default handling

conda-recipe/meta.yaml, docs/source/upcoming_release_notes/337-bld_run_constrained.rst
change the header name in conda-recipe from `run-constrained` to `run_constrained`
I was trying to fix conda feedstocks
ci?
This PR
=> BLD: run_constrained not run-constrained

docs/source/upcoming_release_notes/339-mnt_audit_out.rst, happi/audit.py, happi/cli.py
- gives non-interactive audit tables a max width
- fixes bad logic in table construction
I want audits to be more useful
closes #338 
interactively
This PR
=> MNT: improve `happi audit` output

conda-recipe/meta.yaml, happi/tests/test_backends.py, happi/tests/test_cli.py
- Properly mark `test_multi_backend` as needing pymongo.  (its fixtures had this decorator already, but the test still tried to run 🤷 )
Seen in #343 and others
CI
This PR
=> TST: Properly test with pymongo, adjust profiler usage for py3.12

CONTRIBUTING.rst, README.md, docs/source/containers.rst, docs/source/upcoming_release_notes/345-repair_no_changes.rst
Improve some minor things i noticed while reading the docs for 1st time: fix a few dead links in docs, link from readme to contributing doc so can't miss it, and explicitly list dev instructions
=> DOC: fix a few dead links in docs, small changes to make 1st time dev instructions bit more clear

docs/pre-release-notes.sh, docs/source/upcoming_release_notes/326-pre_release_default_editor.rst
closes #326 
Tested manually
don't think it's necessary for this
=> MNT: make pre-release notes script check if EDITOR is set

README.md, docs/source/upcoming_release_notes/324-repair_no_changes.rst, examples/example.cfg, happi/cli.py, happi/tests/test_cli.py
Make it so running `happi repair` only saves an item if it had a field actually changed during the repair process. This stops the last_edit times from being updated on unchanged items.
Also, it wasn't immediately clear to me how to use the cli along with the example db.json (so I could try commands on a small example db). So added an example cfg and some instructions to the README to make this easy.
closes #324 
Manually tested and verified, and test case added.
In function's doc string and comments.
=> MNT: make happi repair not save items that have no changed fields

docs/source/upcoming_release_notes/349-bug_args_simplenamespace.rst, happi/tests/conftest.py, happi/tests/test_cli.py
In conftest.py, we defined a mock database with some SimpleNamespace devices.  
Jane ran into this, uncovering a poorly written test (very likely my fault)
Many of the tests in happi are also quite brittle.  I'd love to blame someone else for this but I did go through rewriting tests for click and did not fix this problem.
pytest
This PR
=> FIX: make tst_pim_2 loadable, types.SimpleNamespace does not take positional args

dev-requirements.txt, docs/source/upcoming_release_notes/352-bld_pip_profiler.rst
* replaces `line-profiler` with `line_profiler` in `dev-requirements.txt` 
In a very roundabout way trying to get prepped for py3.12.
These two packages seem to be identical on pypi, and typhos already lists the underscore version as a dev-requirement.
the underscore version is available on conda-forge, and prevents confusion/mismatch with our build scripts
CI runs 🤷 Package builds 🤷 
This PR
=> BLD: Try swapping to line_profiler, seems the same as line-profiler

dev-requirements.txt, docs/source/upcoming_release_notes/353-bld_subpackage.rst, gui-requirements.txt, happi/tests/test_qt.py, mongo-requirements.txt, pyproject.toml
Splits happi gui dependencies into subpackages (pip) or separate outputs (conda)
closes #347 
closes #340 
Added some ui tests, but mostly relying on CI here to assess failure
This PR
=> BLD: split ui dependencies into subpackage

docs/source/upcoming_release_notes/357-mnt_cli_annotations.rst, happi/audit.py, happi/cli.py
- Makes the return type for `happi.cli.search_parser` always a list.  Previously this could sometimes return a `Set`
- Runs through a variety of type hinting problems revealed by mypy
- Fixes a straggling reference to `happi.containers.registry._registry`, uses the public API instead (`happi.containers.registry[]`)
- Makes a set -> list conversion in `happi.cli.load` more concise
Closes #354 
I ran `mypy` along the way and ended up doing a bunch of other random things.  Including
- Not overwriting variables when changing types
Makes sure the test still ran, plus some interactive testing
This PR
=> MNT: make happi.cli.search_parser always return a list

docs/source/upcoming_release_notes/360-tst_no_arg.rst, happi/tests/test_cli.py
Update test suite to handle new and old version of click.
Don't check exit code for cli when no arguments are passed
Apparently click < 8.2.0 returned 0 when no args were passed to the cli program.  This was changed to 2 in 8.2.0 to match other cli programs
Interactively, and in CI
This PR
https://github.com/pallets/click/releases/tag/8.2.0
=> TST: update test_cli_no_argument, updated click returns non-zero when no args passed

docs/source/upcoming_release_notes/366-bug_cli_invalid_entry.rst, happi/cli.py, happi/qt/model.py
Handle invalid entries gathered in cli search method, and `HappiViewMixi`
It's possible we actually want to adjust `Client.search` to take an argument that toggles whether or not invalid entries are returned.  Other parts of our stack likely assume everything coming from .search() is valid, and the previous change breaks this assumption.
However, this does prevent us from using that kwarg in a container, and we'd have to be very clear about that documentation.  I've sort of painted myself into a corner here.  I think I'll opt for not changing the behavior of `Client.search` for now.  If we run into significantly more issues or get reports of this behavior breaking things, I'll recosnider.
Previously searching for this would error our due to the new InvalidEntry.  This would prevent the …
=> BUG: properly handle InvalidResult in cli search method
